/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.11u-20020215-2136
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif



#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGEXPORT(void) SWIG_TypeClientData(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif




/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
SWIGEXPORT(PyObject *)        SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own) {
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyInstanceObject *inst;
    inst = PyObject_NEW(PyInstanceObject, &PyInstance_Type);
    if (!inst) return robj;
    inst->in_dict = PyDict_New();
    inst->in_class = (PyClassObject *) type->clientdata;
    Py_INCREF(inst->in_class);
    PyObject_SetAttrString((PyObject *)inst,(char*)"this",robj);
    Py_DECREF(robj);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString((PyObject *)inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = (PyObject *) inst;
    Py_INCREF(robj);
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_SuffixTree swig_types[0] 
#define  SWIGTYPE_p_p_char swig_types[1] 
#define  SWIGTYPE_p_SuffixNode swig_types[2] 
#define  SWIGTYPE_p_p_SuffixNode swig_types[3] 
#define  SWIGTYPE_p_STREE_STRUCT swig_types[4] 
#define  SWIGTYPE_p_int swig_types[5] 
#define  SWIGTYPE_p_SNODE_STRUCT swig_types[6] 
static swig_type_info *swig_types[8];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= SuffixTreec.so
  ------------------------------------------------*/
#define SWIG_init    initSuffixTreec

#define SWIG_name    "SuffixTreec"

static PyObject* l_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyList_Check(target)) {
            o2 = target;
            target = PyList_New(0);
            PyList_Append(target, o2);
	    Py_XDECREF(o2);
        }
        PyList_Append(target,o);
	Py_XDECREF(o);
    }
    return target;
}


static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyTuple_Check(target)) {
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}


#include "SuffixTree.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_SuffixTree_tree_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    STREE_STRUCT *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SuffixTree_tree_set",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_STREE_STRUCT,1)) == -1) return NULL;
    if (arg1) arg1->tree = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_SuffixTree_tree_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    STREE_STRUCT *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixTree_tree_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    result = (STREE_STRUCT *) (arg1->tree);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_STREE_STRUCT, 0);
    return resultobj;
}


static PyObject *_wrap_new_SuffixTree(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 = 128 ;
    struct SuffixTree *result;
    
    if(!PyArg_ParseTuple(args,(char *)"|i:new_SuffixTree",&arg1)) return NULL;
    result = (struct SuffixTree *)new_SuffixTree(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixTree, 1);
    return resultobj;
}


static PyObject *_wrap_delete_SuffixTree(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_SuffixTree",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    delete_SuffixTree(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_SuffixTree_add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osi:SuffixTree_add",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    result = (int )SuffixTree_add(arg1,arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixTree_num_nodes(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixTree_num_nodes",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    result = (int )SuffixTree_num_nodes(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixTree_root(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixTree_root",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixTree_root(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixTree_match(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixTree *arg1 ;
    char *arg2 ;
    SuffixNode **arg3 ;
    int *arg4 ;
    int result;
    SuffixNode *temp3 ;
    int temp4 ;
    PyObject * obj0  = 0 ;
    
    {
        arg3 = &temp3;
    }
    {
        arg4 = &temp4;
    }
    if(!PyArg_ParseTuple(args,(char *)"Os:SuffixTree_match",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixTree,1)) == -1) return NULL;
    result = (int )SuffixTree_match(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = SWIG_NewPointerObj(*((void**)arg3),
        SWIGTYPE_p_SuffixNode,
        1);
        resultobj = t_output_helper(resultobj, o);
    }
    {
        PyObject *o;
        o = PyInt_FromLong((long) (*arg4));
        resultobj = t_output_helper(resultobj, o);
    }
    return resultobj;
}


static PyObject * SuffixTree_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_SuffixTree, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_SuffixNode_tree_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    STREE_STRUCT *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SuffixNode_tree_set",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_STREE_STRUCT,1)) == -1) return NULL;
    if (arg1) arg1->tree = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_SuffixNode_tree_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    STREE_STRUCT *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_tree_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (STREE_STRUCT *) (arg1->tree);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_STREE_STRUCT, 0);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_node_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SNODE_STRUCT *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:SuffixNode_node_set",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_SNODE_STRUCT,1)) == -1) return NULL;
    if (arg1) arg1->node = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_SuffixNode_node_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SNODE_STRUCT *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_node_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SNODE_STRUCT *) (arg1->node);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SNODE_STRUCT, 0);
    return resultobj;
}


static PyObject *_wrap_delete_SuffixNode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_SuffixNode",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    delete_SuffixNode(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_SuffixNode_num_children(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_num_children",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_num_children(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_find_child(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    char arg2 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oc:SuffixNode_find_child",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixNode_find_child(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_children(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_children",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixNode_children(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_next",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixNode_next(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_parent(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_parent",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixNode_parent(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_suffix_link(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    SuffixNode *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_suffix_link",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (SuffixNode *)SuffixNode_suffix_link(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 1);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_edgelen(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_edgelen",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_edgelen(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_edgestr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_edgestr",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (char *)SuffixNode_edgestr(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    {
        free(result);
    }
    return resultobj;
}


static PyObject *_wrap_SuffixNode_getch(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_getch",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (char *)SuffixNode_getch(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    {
        free(result);
    }
    return resultobj;
}


static PyObject *_wrap_SuffixNode_labellen(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_labellen",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_labellen(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_labelstr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_labelstr",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (char *)SuffixNode_labelstr(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    {
        free(result);
    }
    return resultobj;
}


static PyObject *_wrap_SuffixNode_ident(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_ident",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_ident(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_num_leaves(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:SuffixNode_num_leaves",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_num_leaves(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SuffixNode_leaf(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *arg1 ;
    int arg2 ;
    char **arg3 ;
    int *arg4 ;
    int *arg5 ;
    int result;
    char *ignore3 ;
    int temp4 ;
    int temp5 ;
    PyObject * obj0  = 0 ;
    
    {
        arg3 = &ignore3;
    }
    {
        arg4 = &temp4;
    }
    {
        arg5 = &temp5;
    }
    if(!PyArg_ParseTuple(args,(char *)"Oi:SuffixNode_leaf",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_SuffixNode,1)) == -1) return NULL;
    result = (int )SuffixNode_leaf(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    {
        resultobj = (*arg3) ? PyString_FromString(*arg3) : Py_BuildValue((char*)"");
        free(*arg3);
    }
    {
        PyObject *o;
        o = PyInt_FromLong((long) (*arg4));
        resultobj = t_output_helper(resultobj, o);
    }
    {
        PyObject *o;
        o = PyInt_FromLong((long) (*arg5));
        resultobj = t_output_helper(resultobj, o);
    }
    return resultobj;
}


static PyObject *_wrap_new_SuffixNode(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct SuffixNode *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_SuffixNode")) return NULL;
    result = (struct SuffixNode *)(struct SuffixNode *) calloc(1, sizeof(struct SuffixNode));
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_SuffixNode, 0);
    return resultobj;
}


static PyObject * SuffixNode_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_SuffixNode, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"SuffixTree_tree_set", _wrap_SuffixTree_tree_set, METH_VARARGS },
	 { (char *)"SuffixTree_tree_get", _wrap_SuffixTree_tree_get, METH_VARARGS },
	 { (char *)"new_SuffixTree", _wrap_new_SuffixTree, METH_VARARGS },
	 { (char *)"delete_SuffixTree", _wrap_delete_SuffixTree, METH_VARARGS },
	 { (char *)"SuffixTree_add", _wrap_SuffixTree_add, METH_VARARGS },
	 { (char *)"SuffixTree_num_nodes", _wrap_SuffixTree_num_nodes, METH_VARARGS },
	 { (char *)"SuffixTree_root", _wrap_SuffixTree_root, METH_VARARGS },
	 { (char *)"SuffixTree_match", _wrap_SuffixTree_match, METH_VARARGS },
	 { (char *)"SuffixTree_swigregister", SuffixTree_swigregister, METH_VARARGS },
	 { (char *)"SuffixNode_tree_set", _wrap_SuffixNode_tree_set, METH_VARARGS },
	 { (char *)"SuffixNode_tree_get", _wrap_SuffixNode_tree_get, METH_VARARGS },
	 { (char *)"SuffixNode_node_set", _wrap_SuffixNode_node_set, METH_VARARGS },
	 { (char *)"SuffixNode_node_get", _wrap_SuffixNode_node_get, METH_VARARGS },
	 { (char *)"delete_SuffixNode", _wrap_delete_SuffixNode, METH_VARARGS },
	 { (char *)"SuffixNode_num_children", _wrap_SuffixNode_num_children, METH_VARARGS },
	 { (char *)"SuffixNode_find_child", _wrap_SuffixNode_find_child, METH_VARARGS },
	 { (char *)"SuffixNode_children", _wrap_SuffixNode_children, METH_VARARGS },
	 { (char *)"SuffixNode_next", _wrap_SuffixNode_next, METH_VARARGS },
	 { (char *)"SuffixNode_parent", _wrap_SuffixNode_parent, METH_VARARGS },
	 { (char *)"SuffixNode_suffix_link", _wrap_SuffixNode_suffix_link, METH_VARARGS },
	 { (char *)"SuffixNode_edgelen", _wrap_SuffixNode_edgelen, METH_VARARGS },
	 { (char *)"SuffixNode_edgestr", _wrap_SuffixNode_edgestr, METH_VARARGS },
	 { (char *)"SuffixNode_getch", _wrap_SuffixNode_getch, METH_VARARGS },
	 { (char *)"SuffixNode_labellen", _wrap_SuffixNode_labellen, METH_VARARGS },
	 { (char *)"SuffixNode_labelstr", _wrap_SuffixNode_labelstr, METH_VARARGS },
	 { (char *)"SuffixNode_ident", _wrap_SuffixNode_ident, METH_VARARGS },
	 { (char *)"SuffixNode_num_leaves", _wrap_SuffixNode_num_leaves, METH_VARARGS },
	 { (char *)"SuffixNode_leaf", _wrap_SuffixNode_leaf, METH_VARARGS },
	 { (char *)"new_SuffixNode", _wrap_new_SuffixNode, METH_VARARGS },
	 { (char *)"SuffixNode_swigregister", SuffixNode_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_SuffixTree[] = {{"_p_SuffixTree", 0, "SuffixTree *"},{"_p_SuffixTree"},{0}};
static swig_type_info _swigt__p_p_char[] = {{"_p_p_char", 0, "char **"},{"_p_p_char"},{0}};
static swig_type_info _swigt__p_SuffixNode[] = {{"_p_SuffixNode", 0, "SuffixNode *"},{"_p_SuffixNode"},{0}};
static swig_type_info _swigt__p_p_SuffixNode[] = {{"_p_p_SuffixNode", 0, "SuffixNode **"},{"_p_p_SuffixNode"},{0}};
static swig_type_info _swigt__p_STREE_STRUCT[] = {{"_p_STREE_STRUCT", 0, "STREE_STRUCT *"},{"_p_STREE_STRUCT"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *"},{"_p_int"},{0}};
static swig_type_info _swigt__p_SNODE_STRUCT[] = {{"_p_SNODE_STRUCT", 0, "SNODE_STRUCT *"},{"_p_SNODE_STRUCT"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_SuffixTree, 
_swigt__p_p_char, 
_swigt__p_SuffixNode, 
_swigt__p_p_SuffixNode, 
_swigt__p_STREE_STRUCT, 
_swigt__p_int, 
_swigt__p_SNODE_STRUCT, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"MAXNUMNODES", (long) (1<<23), 0, 0, 0},
{ SWIG_PY_INT,     (char *)"MAXALPHA", (long) (1<<7), 0, 0, 0},
{ SWIG_PY_INT,     (char *)"STREE_DNA", (long) -1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"STREE_RNA", (long) -1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"STREE_PROTEIN", (long) -2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"STREE_ASCII", (long) 128, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

